// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RodajeIA.Web.Datos;

#nullable disable

namespace RodajeIA.Web.Datos.Migraciones
{
    [DbContext(typeof(RodajeDbContext))]
    partial class RodajeDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.12");

            modelBuilder.Entity("RodajeIA.Web.Datos.Personaje", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("DescripcionFisica")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Edad")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Heridas")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Peinado")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Personalidad")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Rol")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("SerieId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Vestuario")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("SerieId", "Nombre")
                        .IsUnique();

                    b.ToTable("Personajes");
                });

            modelBuilder.Entity("RodajeIA.Web.Datos.Serie", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Series");
                });

            modelBuilder.Entity("RodajeIA.Web.Datos.Personaje", b =>
                {
                    b.HasOne("RodajeIA.Web.Datos.Serie", "Serie")
                        .WithMany("Personajes")
                        .HasForeignKey("SerieId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Serie");
                });

            modelBuilder.Entity("RodajeIA.Web.Datos.Serie", b =>
                {
                    b.Navigation("Personajes");
                });
#pragma warning restore 612, 618
        }
    }
}
